/**
 * FocusGuard Blocklist Data
 * Comprehensive list of adult/pornographic domains and keyword filters.
 * Used by the background service worker for URL blocking.
 */
const BlocklistData = (function () {
  // =====================================================================
  // BLOCKED DOMAINS — 500+ known adult/pornographic sites by category
  // =====================================================================
  const BLOCKED_DOMAINS = [
    // === Major Tube Sites ===
    'pornhub.com',
    'xvideos.com',
    'xnxx.com',
    'xhamster.com',
    'redtube.com',
    'youporn.com',
    'tube8.com',
    'spankbang.com',
    'eporner.com',
    'pornone.com',
    'ixxx.com',
    'fuq.com',
    'porntrex.com',
    'hqporner.com',
    'tnaflix.com',
    'drtuber.com',
    'slutload.com',
    'thumbzilla.com',
    'beeg.com',
    'porndig.com',
    'anyporn.com',
    'txxx.com',
    'vporn.com',
    'nuvid.com',
    'pornhd.com',
    'porn300.com',
    'porntube.com',
    'sunporno.com',
    'empflix.com',
    'tubegalore.com',
    'youjizz.com',
    'gotporn.com',
    'pornrox.com',
    'pornzog.com',
    'pornhat.com',
    'sxyprn.com',
    'porn00.org',
    'cliphunter.com',
    'tubewolf.com',
    'fux.com',
    'megatube.xxx',
    'fapvid.com',
    'pornoxo.com',
    'porn.com',
    'sex.com',
    'xxxbunker.com',
    'dinotube.com',
    'fapcat.com',
    'freeones.com',
    'ashemaletube.com',
    'sheshaft.com',

    // === Premium / Paysite Networks ===
    'brazzers.com',
    'realitykings.com',
    'bangbros.com',
    'naughtyamerica.com',
    'digitalplayground.com',
    'babes.com',
    'mofos.com',
    'twistys.com',
    'wicked.com',
    'vivid.com',
    'kink.com',
    'evilangel.com',
    'julesjordan.com',
    'vixen.com',
    'blacked.com',
    'tushy.com',
    'deeper.com',
    'slayed.com',
    'milfy.com',
    'adulttime.com',
    'pornpros.com',
    'teamskeet.com',
    'milfed.com',
    'puremature.com',
    'passion-hd.com',
    'fantasyhd.com',
    'tiny4k.com',
    'lubed.com',
    'holed.com',
    'povd.com',
    'cum4k.com',
    'spyfam.com',
    'nannyspy.com',
    'exotic4k.com',
    'castingcouch-hd.com',
    'propertysex.com',
    'fakehub.com',
    'faketaxi.com',
    'fakehospital.com',
    'fakeagent.com',
    'sexart.com',
    'metart.com',
    'metartx.com',
    'met-art.com',
    'x-art.com',
    'hegre.com',
    'femjoy.com',
    'doghousedigital.com',
    'devilsfilm.com',
    'sweetsinner.com',
    'newsensations.com',
    'girlsway.com',
    'iconmale.com',
    'men.com',
    'seancody.com',
    'corbinasfisher.com',
    'activeduty.com',
    'nextdoorstudios.com',
    'falconstudios.com',
    'ragingstallion.com',

    // === Cam / Live Sites ===
    'chaturbate.com',
    'bongacams.com',
    'livejasmin.com',
    'camsoda.com',
    'cam4.com',
    'stripchat.com',
    'imlive.com',
    'flirt4free.com',
    'myfreecams.com',
    'streamate.com',
    'cams.com',
    'jerkmate.com',
    'adultwork.com',
    'babestation.com',
    'camcontacts.com',
    'xlovecam.com',
    'camster.com',
    'xcams.com',
    'camonster.com',
    'camrabbit.com',
    'sakuralive.com',
    'bimbim.com',
    'royalcams.com',
    'camversity.com',
    'amateur.tv',
    'cams4free.com',
    'camwhores.tv',
    'recurbate.com',

    // === Fan / Creator Platforms (Adult) ===
    'onlyfans.com',
    'fansly.com',
    'manyvids.com',
    'clips4sale.com',
    'justfor.fans',
    'loyalfans.com',
    'fancentro.com',
    'frisk.chat',
    'alua.com',
    'sextpanther.com',
    'iwantclips.com',
    'modelhub.com',
    'pornhubpremium.com',
    'bellesa.co',
    'sssh.com',

    // === Hentai / Anime / Drawn ===
    'nhentai.net',
    'hentaihaven.org',
    'hanime.tv',
    'rule34.xxx',
    'fakku.net',
    'gelbooru.com',
    'sankakucomplex.com',
    'rule34.paheal.net',
    'e-hentai.org',
    'exhentai.org',
    'hitomi.la',
    'hentai2read.com',
    'hentaihere.com',
    'hentaimama.io',
    'hentaigasm.com',
    'hentaistream.com',
    'muchohentai.com',
    'tsumino.com',
    'pururin.to',
    'simply-hentai.com',
    'doujins.com',
    'hentaifox.com',
    'imhentai.xxx',
    'luscious.net',
    'multporn.net',
    'naughtycomics.net',
    'naughtyatwork.org',
    'shadbase.com',
    'koushoku.org',
    'mangahentai.me',
    'hentainexus.com',
    'hbrowse.com',
    'myreadingmanga.info',
    'cartoon-sex.com',
    'cartoonpornvideos.com',
    'rule34video.com',

    // === Image Galleries / Aggregators ===
    'imagefap.com',
    'nudevista.com',
    'fapdu.com',
    'pornpics.com',
    'pornpics.de',
    'babepedia.com',
    'kindgirls.com',
    'brdteengal.com',
    'elitebabes.com',
    'hegre-art.com',
    'thelifeerotic.com',
    'femjoyhunter.com',
    'metarthunter.com',
    'morazzia.com',
    'errotica-archives.com',
    'xfantazy.com',
    'hegreart.com',
    'eroticbeauties.net',
    'foxhq.com',
    'bustybloom.com',
    'girlsofdesire.org',
    'x-angels.com',
    'alsscan.com',
    'inthecrack.com',
    'mcnudes.com',
    'domai.com',
    'eroutique.com',
    'zemani.com',
    'stunning18.com',
    'rylskyart.com',
    'eroticbeauty.com',

    // === Forums / Communities ===
    'planetsuzy.org',
    'phun.org',
    'forumophilia.com',
    'freeusenet.nl',
    'adultdeepfakes.com',
    'mrdeepfakes.com',
    'celebjihad.com',
    'celeb.gate.cc',
    'thefappeningblog.com',
    'nudecelebforum.com',
    'famousboard.com',
    'aznude.com',
    'nudography.com',
    'ancensored.com',
    'boobpedia.com',

    // === Erotic Stories / Literature ===
    'literotica.com',
    'sexstories.com',
    'storiesonline.net',
    'asstr.org',
    'bdsmlibrary.com',
    'nifty.org',
    'mcstories.com',
    'chyoa.com',

    // === Dating / Hookup / Escort ===
    'adultfriendfinder.com',
    'ashleymadison.com',
    'benaughty.com',
    'fling.com',
    'alt.com',
    'fetlife.com',
    'collarspace.com',
    'swinglifestyle.com',
    'kasidie.com',
    'sdc.com',
    'feeld.co',
    'tryst.link',
    'eros.com',
    'erosguide.com',
    'rubmaps.ch',
    'listcrawler.com',
    'escortdirectory.com',
    'skipthegames.com',
    'bedpage.com',
    'megapersonals.com',
    'privatedelights.ch',
    'slixa.com',
    'eroticmonkey.ch',
    'leolist.cc',

    // === Reddit-like / Social (Adult-specific) ===
    'scrolller.com',
    'lewdweb.net',
    'coomer.su',
    'coomer.party',
    'kemono.su',
    'kemono.party',
    'fapello.com',
    'thothub.to',
    'simpcity.su',
    'leakedbb.com',
    'socialmediagirls.com',
    'nudostar.com',
    'hotleak.vip',
    'thotsbay.com',

    // === Aggregators / Search Engines (Adult) ===
    'alohatube.com',
    'lobstertube.com',
    'pornmd.com',
    'pornwhite.com',
    'fullporner.com',
    'collectionofbestporn.com',
    'booloo.com',
    'tubev.sex',
    'tiava.com',
    'xxxdan.com',
    'definebabe.com',
    'babesource.com',
    'smutr.com',
    'freeomovie.to',
    'erothots.com',
    'thepornmap.com',

    // === Amateur / User-Generated ===
    'xfreehd.com',
    'homemoviestube.com',
    'amateurporn.com',
    'reallifecam.com',
    'voyeurhit.com',
    'voyeurhouse.tv',
    'terk.nl',
    'findtubes.com',
    'motherless.com',
    'heavy-r.com',
    'efukt.com',
    'theync.com',

    // === Asian Adult ===
    'javhd.com',
    'javlibrary.com',
    'r18.com',
    'caribbeancom.com',
    '1pondo.tv',
    'tokyohot.com',
    'heyzo.com',
    'dmm.co.jp',
    'javmost.com',
    'javfree.sh',
    'missav.com',
    'thisav.com',
    'jable.tv',
    'avgle.com',
    'supjav.com',
    'javbangers.com',
    'javseen.tv',
    'javgg.net',
    'onejav.com',
    'javdoe.sh',
    'kissjav.com',
    'njav.tv',
    'javhub.net',

    // === German / European ===
    'mydirtyhobby.com',
    'mydirtyhobby.de',
    'fundorado.de',
    'amateurcommunity.com',
    'big7.com',
    'visit-x.net',
    'xhamsterlive.com',
    'eroprofile.com',

    // === Latin / Spanish ===
    'sexmex.xxx',
    'culioneros.com',

    // === Gay Adult ===
    'gaytube.com',
    'boyfriendtv.com',
    'gaymaletube.com',
    'adam4adam.com',
    'manhunt.net',
    'rentmen.com',
    'squirt.org',
    'xtube.com',
    'gayfuror.com',
    'thisvid.com',

    // === Fetish / BDSM / Niche ===
    'ballbusting.org',
    'bdsmstreak.com',
    'femdomempire.com',
    'meantube.com',
    'footfetishbb.com',
    'wikifeet.com',
    'wikifeetx.com',
    'fetishpapa.com',
    'hentai-foundry.com',
    'deviantclip.com',

    // === Additional Tube & Streaming Sites ===
    'zbporn.com',
    'ok.xxx',
    'tubesafari.com',
    'tubxporn.xxx',
    'perfectgirls.net',
    'perfectgirls.xxx',
    'pichunter.com',
    'freeporn.com',
    'freeporn8.com',
    'freesexvideos.com',
    'sexvid.xxx',
    'xbabe.com',
    'youx.xxx',
    'proporn.com',
    'pornlib.com',
    'pornbimbo.com',
    'maturetube.com',
    'maturetubehere.com',
    'milfmovs.com',
    'milfporn.com',
    'milfsex.com',
    'milf.com',
    'tits.com',
    'boobs.com',
    'ass.com',
    'pussy.com',
    'hotmovs.com',
    'hotscope.tv',
    'analdin.com',
    'analmom.com',
    'analvids.com',
    'analacrobats.com',
    'bangbrosnetwork.com',
    'bigtitsroundasses.com',
    'cumlouder.com',
    'daftsex.com',
    'damplips.com',
    'dansmovies.com',
    'desiporn.tube',
    'desixxxtube.com',
    'dirtyship.com',
    'extremetube.com',
    'f95zone.to',
    'faapy.com',
    'fap18.net',
    'fapster.xxx',
    'freehdinterracial.com',
    'freepornvideo.sex',
    'fresno-ede.org',
    'ghettotube.com',
    'girlsdoporn.com',
    'girlsgonewild.com',
    'gonzo4free.com',
    'good-pornography.com',
    'hdpornvideo.xxx',
    'hellporno.com',
    'hentaicloud.com',
    'hentaicovid.com',
    'hentaidude.com',
    'hentaipros.com',
    'hentaiworld.tv',
    'hoes.tube',
    'hotguysfuck.com',
    'hotporndir.com',
    'ifeelmyself.com',
    'indianpornvideos.com',
    'indiansexmms.net',
    'indiaporn.net',
    'jav321.com',
    'javfinder.la',
    'javgiga.com',
    'javplayer.com',
    'javporn.best',
    'javtorrent.re',
    'javus.com',
    'justswallows.com',
    'largehdtube.com',
    'largeporntube.com',
    'luxuretv.com',
    'madthumbs.com',
    'masturbation.com',
    'maturealbum.com',
    'matureclub.com',
    'melonstube.com',
    'metatube.com',
    'milffox.com',
    'milftoon.xxx',
    'mylust.com',
    'myporngay.com',
    'mysexgames.com',
    'nastyvideotube.com',
    'newchloe18.com',
    'newgrounds.com',
    'nextdoorraw.com',
    'nhentai.to',
    'niceporn.xxx',
    'nightflirt.com',
    'noodlemagazine.com',
    'nubilefilms.com',
    'nubiles.com',
    'nubiles.net',
    'nudecollect.com',
    'nudevoyeurvideos.com',
    'nurumassage.com',
    'oh-anal.com',
    'oldgoesyoung.com',
    'onlyporn.to',
    'only-teen-blowjobs.com',
    'ooporn.com',
    'overflowingbras.com',
    'palimas.com',
    'pandamovies.pw',
    'pervclips.com',
    'petardas.com',
    'phica.net',
    'pinkfineart.com',
    'pleasuregirl.net',
    'plumperd.com',
    'porn555.com',
    'pornbb.org',
    'porncoven.com',
    'porndroids.com',
    'porndude.com',
    'porneq.com',
    'pornerbros.com',
    'pornflip.com',
    'pornfun.com',
    'porngem.com',
    'porngo.com',
    'pornheed.com',
    'pornhits.com',
    'pornhub.org',
    'pornkai.com',
    'pornmaki.com',
    'pornmz.com',
    'pornner.com',
    'pornoeggs.com',
    'pornolab.net',
    'pornoreino.com',
    'pornrabbit.com',
    'pornsos.com',
    'pornstarslikeitbig.com',
    'porntop.com',
    'porntry.com',
    'porntvee.com',
    'pornve.com',
    'pornxs.com',
    'privatehomeclips.com',
    'pussyspace.com',
    'pussyspot.net',
    'r34anim.com',
    'realgfporn.com',
    'realitylovers.com',
    'realsexpass.com',
    'redgifs.com',
    'redwap.me',
    'ruleporn.com',
    'rule34hentai.net',
    'sextb.net',
    'sextubesearch.com',
    'sextvx.com',
    'sexu.com',
    'sexyandfunny.com',
    'sexygirlsalbum.com',
    'shemalestar.com',
    'shemales.com',
    'shemalestube.com',
    'shooshtime.com',
    'silverdaddies.com',
    'slutroulette.com',
    'smutty.com',
    'tabooporns.com',
    'teensnow.com',
    'theporndude.com',
    'thothub.tv',
    'titsintops.com',
    'tktube.com',
    'tokyomotion.net',
    'tubedupe.com',
    'tubepornstars.com',
    'tuberel.com',
    'tubevector.com',
    'tumbex.com',
    'twistysnetwork.com',
    'updatetube.com',
    'upornia.com',
    'vidz.com',
    'vintageerotica.com',
    'vivud.com',
    'watchmygf.me',
    'watchmyexgf.net',
    'wetplace.com',
    'wetpussy.com',
    'worldsex.com',
    'xcafe.com',
    'xerotica.com',
    'xfantasy.com',
    'xgroovy.com',
    'xmegadrive.com',
    'xmoviesforyou.com',
    'xpee.com',
    'xtapes.to',
    'xtwisted.com',
    'xxbrits.com',
    'xxxfiles.com',
    'xxxymovies.com',
    'youramateurporn.com',
    'yourdailypornstars.com',
    'yourdailypornvideos.com',
    'zporn.com',
  ];

  // =====================================================================
  // BLOCKED KEYWORDS — terms that trigger blocking when found in a URL
  // Designed to catch sites not in the domain list while avoiding
  // false positives on legitimate sites.
  // =====================================================================
  const BLOCKED_KEYWORDS = [
    'porn',
    'xxx',
    'hentai',
    'nsfw',
    'xvideos',
    'xhamster',
    'xnxx',
    'redtube',
    'youporn',
    'pornhub',
    'brazzers',
    'chaturbate',
    'camgirl',
    'camshow',
    'livesex',
    'sexcam',
    'webcamsex',
    'camsex',
    'cybersex',
    'phonesex',
    'nudes',
    'onlyfans',
    'fansly',
    'blowjob',
    'handjob',
    'gangbang',
    'threesome',
    'milf',
    'dildo',
    'vibrator',
    'buttplug',
    'fleshlight',
    'anal-sex',
    'cunnilingus',
    'fellatio',
    'bukkake',
    'creampie',
    'deepthroat',
    'facesitting',
    'footjob',
    'titjob',
    'squirting',
    'orgasm',
    'bondage',
    'femdom',
    'bdsm',
    'dominatrix',
    'fetish',
    'hentaihaven',
    'rule34',
    'nhentai',
    'doujin',
    'ahegao',
    'futanari',
    'tentacle',
    'erotica',
    'nudist',
    'swingers',
    'hotwife',
    'cuckold',
    'slutwife',
    'escort-service',
    'callgirl',
    'jerkoff',
    'masturbat',
    'wank',
  ];

  // =====================================================================
  // MATCHING FUNCTIONS
  // =====================================================================

  /**
   * Check if a hostname matches any domain in the built-in or custom list.
   * Supports exact match and subdomain match (e.g., www.pornhub.com matches pornhub.com).
   */
  function isDomainBlocked(hostname, customDomains) {
    if (!hostname) return false;
    const lowerHost = hostname.toLowerCase().replace(/^www\./, '');
    const allDomains = customDomains
      ? [...BLOCKED_DOMAINS, ...customDomains]
      : BLOCKED_DOMAINS;
    return allDomains.some(
      (domain) => lowerHost === domain || lowerHost.endsWith('.' + domain)
    );
  }

  /**
   * Check if a URL contains any blocked keyword.
   * Uses word-boundary matching to avoid false positives
   * (e.g., "therapist" won't trigger "rape", "essex" won't trigger "sex").
   */
  function isKeywordBlocked(url) {
    if (!url) return false;
    // Only check the hostname + path, not the full URL with protocol
    const lowerUrl = String(url).toLowerCase();
    return BLOCKED_KEYWORDS.some((keyword) => {
      // For short keywords that could cause false positives, use word boundary
      if (keyword.length <= 4) {
        // Check if keyword appears as its own segment (between dots, slashes, hyphens, underscores)
        const regex = new RegExp(
          `(?:^|[./?&=_\\-])${keyword}(?:$|[./?&=_\\-])`,
          'i'
        );
        return regex.test(lowerUrl);
      }
      // For longer keywords, a simple includes is safe enough
      return lowerUrl.includes(keyword);
    });
  }

  /**
   * Master check: is this URL blocked by domain OR keyword?
   */
  function isBlocked(url, customDomains) {
    try {
      const parsedUrl = new URL(url);
      return (
        isDomainBlocked(parsedUrl.hostname, customDomains) ||
        isKeywordBlocked(url)
      );
    } catch (e) {
      // If URL parsing fails, fall back to keyword check
      return isKeywordBlocked(url);
    }
  }

  return {
    BLOCKED_DOMAINS,
    BLOCKED_KEYWORDS,
    isBlocked,
    isDomainBlocked,
    isKeywordBlocked,
  };
})();

// Support both service worker importScripts and module environments
if (typeof module !== 'undefined') module.exports = BlocklistData;
